excerpt_separator: ""
markdown: kramdown
url: http://xymor.github.io
title: Coder in the sky with diamonds
tagline: thoughts on code and tech
description: thoughts on code and tech
paginate: 5
